-- This script will be executed automatically when the PostgreSQL container starts.

-- Create the 'users' table if it doesn't already exist.
CREATE TABLE IF NOT EXISTS users (
    -- A unique identifier for each user, generated by the application.
                                     id UUID PRIMARY KEY,

    -- The user's bank account number. It must be unique to prevent duplicates.
                                     account_number TEXT NOT NULL UNIQUE,

    -- The user's IFSC code.
                                     ifsc_code TEXT NOT NULL,

    -- The name of the bank, fetched from the external API.
                                     bank_name TEXT NOT NULL,

    -- The specific branch name, fetched from the external API.
                                     branch TEXT NOT NULL,

    -- The full address of the bank branch. Nullable in case the API doesn't provide it.
                                     address TEXT,

    -- The city and pincode of the bank branch. Nullable.
                                     city TEXT,

    -- The state code (e.g., "IN-DL"). Nullable.
                                     state_code TEXT,

    -- The routing number, often the same as the IFSC. Nullable.
                                     routing_no TEXT,

    -- A timestamp automatically set to the time the user was created.
                                     created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
